In [1]:
import numpy as np 
import pandas as pd

In [7]:
series=pd.Series(data=[78,92,36,64,89])
series

0    78
1    92
2    36
3    64
4    89
dtype: int64

In [8]:
series.values

array([78, 92, 36, 64, 89])

In [9]:
series.index

RangeIndex(start=0, stop=5, step=1)

In [10]:
series[1]

92

In [11]:
series[1:3]

1    92
2    36
dtype: int64

In [12]:
data=[700000,800000,1600000,1800000,3000000]
index=['Swift','Jazz','Civic','Altis','Gallardo']

series = pd.Series(data,index)
series

Swift        700000
Jazz         800000
Civic       1600000
Altis       1800000
Gallardo    3000000
dtype: int64

In [13]:
series['Swift']

700000

In [14]:
series['Jazz' : 'Gallardo']

Jazz         800000
Civic       1600000
Altis       1800000
Gallardo    3000000
dtype: int64

In [15]:
carPrice_dict={ 
    'Swift':700000,
    'Jazz':800000,
    'Civic':1600000,
    'Altis':1800000,
    'Gallardo':3000000
}

car_price = pd.Series(carPrice_dict)
car_price

Swift        700000
Jazz         800000
Civic       1600000
Altis       1800000
Gallardo    3000000
dtype: int64

In [16]:
car_man_dict={
    'Swift':'Maruti',
    'Jazz':'Honda',
    'Civic':'Honda',
    'Altis':'Toyota',
    'Gallardo':'Lamborghini'
}

car_man=pd.Series(car_man_dict)
print(car_price)
print(car_man)

Swift        700000
Jazz         800000
Civic       1600000
Altis       1800000
Gallardo    3000000
dtype: int64
Swift            Maruti
Jazz              Honda
Civic             Honda
Altis            Toyota
Gallardo    Lamborghini
dtype: str

In [17]:
cars= pd.DataFrame({'Price':car_price , 'Manufacturer':car_man})
cars

            Price Manufacturer
Swift      700000       Maruti
Jazz       800000        Honda
Civic     1600000        Honda
Altis     1800000       Toyota
Gallardo  3000000  Lamborghini

In [19]:
cars['Price']

Swift        700000
Jazz         800000
Civic       1600000
Altis       1800000
Gallardo    3000000
Name: Price, dtype: int64

In [20]:
cars['Manufacturer']

Swift            Maruti
Jazz              Honda
Civic             Honda
Altis            Toyota
Gallardo    Lamborghini
Name: Manufacturer, dtype: str

In [24]:
car_price
pd.DataFrame(car_price,columns=['Car Price'])

          Car Price
Swift        700000
Jazz         800000
Civic       1600000
Altis       1800000
Gallardo    3000000

In [25]:
data=[
    {'Name':'Subodh', 'Marks':28},
    {'Name':'Ram','Marks':27},
    {'Name':'Abdul','Marks':26},
    {'Name':'John','Marks':38}
]

pd.DataFrame(data)

     Name  Marks
0  Subodh     28
1     Ram     27
2   Abdul     26
3    John     38

In [26]:
pd.DataFrame(
    [{'Subodh':20 ,'Ram':25},
     {'Abdul':29,'John':24}
     ],
     index=['Maths','Physics']
)

         Subodh   Ram  Abdul  John
Maths      20.0  25.0    NaN   NaN
Physics     NaN   NaN   29.0  24.0

In [29]:
data_json=pd.read_json('example.json')
data_json

     Duration  Pulse  Maxpulse  Calories
0          60    110       130     409.1
1          60    117       145     479.0
2          60    103       135     340.0
3          45    109       175     282.4
4          45    117       148     406.0
..        ...    ...       ...       ...
164        60    105       140     290.8
165        60    110       145     300.4
166        60    115       145     310.2
167        75    120       150     320.4
168        75    125       150     330.4

[169 rows x 4 columns]