In [1]:
import numpy as np
import pandas as pd

# Problem Statement:
The teacher does not want to reveal the marks of students who have failed. The condition is that if a student has scored marks >= 33, then they have passed, otherwise failed. The marks of failed students has to be replaced with ‘Fail’. So, how can the task be performed?.

# Solution :

In [3]:
marks = [{'Chemistry': 67, 'Physics': 45, 'Mathematics': 50, 'English' : 19},
        {'Chemistry': 90, 'Physics': 92, 'Mathematics': 87, 'English' : 90}, 
        {'Chemistry': 66, 'Physics': 72, 'Mathematics': 81, 'English' : 72}, 
        {'Chemistry': 32, 'Physics': 40, 'Mathematics': 12, 'English' : 68}]

marks_df = pd.DataFrame(marks , index=['Subodh','Ram','Anil','John'])
marks_df

        Chemistry  Physics  Mathematics  English
Subodh         67       45           50       19
Ram            90       92           87       90
Anil           66       72           81       72
John           32       40           12       68

# DataFrame.mask(cond, other = nan, inplace = False, axis = None)
  cond – Where cond is False, keep the original value. Where True, replace with corresponding value from other

       other - Entries where cond is True are replaced with corresponding value from other.

       inplace - Whether to perform the operation in place on the data.

       axis – alignment axis

In [5]:
fail = marks_df<33
marks_df.mask(fail,'Fail')

       Chemistry  Physics Mathematics English
Subodh        67       45          50    Fail
Ram           90       92          87      90
Anil          66       72          81      72
John        Fail       40        Fail      68