In [2]:
import numpy as np
import pandas as pd

In [3]:
df = pd.read_csv('auto_mpg.csv')
df

,mpg,cylinders,displacement,horsepower,weight,acceleration,model_year,origin,name
0,18.0,8,307.0,130.0,3504,12.0,70,usa,chevrolet chevelle malibu
1,15.0,8,350.0,165.0,3693,11.5,70,usa,buick skylark 320
2,18.0,8,318.0,150.0,3436,11.0,70,usa,plymouth satellite
3,16.0,8,304.0,150.0,3433,12.0,70,usa,amc rebel sst
4,17.0,8,302.0,140.0,3449,10.5,70,usa,ford torino
...,...,...,...,...,...,...,...,...,...
393,27.0,4,140.0,86.0,2790,15.6,82,usa,ford mustang gl
394,44.0,4,97.0,52.0,2130,24.6,82,europe,vw pickup
395,32.0,4,135.0,84.0,2295,11.6,82,usa,dodge rampage
396,28.0,4,120.0,79.0,2625,18.6,82,usa,ford ranger
397,31.0,4,119.0,82.0,2720,19.4,82,usa,chevy s-10

In [4]:
df.head()

,mpg,cylinders,displacement,horsepower,weight,acceleration,model_year,origin,name
0,18.0,8,307.0,130.0,3504,12.0,70,usa,chevrolet chevelle malibu
1,15.0,8,350.0,165.0,3693,11.5,70,usa,buick skylark 320
2,18.0,8,318.0,150.0,3436,11.0,70,usa,plymouth satellite
3,16.0,8,304.0,150.0,3433,12.0,70,usa,amc rebel sst
4,17.0,8,302.0,140.0,3449,10.5,70,usa,ford torino

In [5]:
df.tail()

,mpg,cylinders,displacement,horsepower,weight,acceleration,model_year,origin,name
393,27.0,4,140.0,86.0,2790,15.6,82,usa,ford mustang gl
394,44.0,4,97.0,52.0,2130,24.6,82,europe,vw pickup
395,32.0,4,135.0,84.0,2295,11.6,82,usa,dodge rampage
396,28.0,4,120.0,79.0,2625,18.6,82,usa,ford ranger
397,31.0,4,119.0,82.0,2720,19.4,82,usa,chevy s-10

In [6]:
df.describe()

,mpg,cylinders,displacement,horsepower,weight,acceleration,model_year
count,398.000000,398.000000,398.000000,392.000000,398.000000,398.000000,398.000000
mean,23.514573,5.454774,193.425879,104.469388,2970.424623,15.568090,76.010050
std,7.815984,1.701004,104.269838,38.491160,846.841774,2.757689,3.697627
min,9.000000,3.000000,68.000000,46.000000,1613.000000,8.000000,70.000000
25%,17.500000,4.000000,104.250000,75.000000,2223.750000,13.825000,73.000000
50%,23.000000,4.000000,148.500000,93.500000,2803.500000,15.500000,76.000000
75%,29.000000,8.000000,262.000000,126.000000,3608.000000,17.175000,79.000000
max,46.600000,8.000000,455.000000,230.000000,5140.000000,24.800000,82.000000

In [7]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 398 entries, 0 to 397
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   mpg           398 non-null    float64
 1   cylinders     398 non-null    int64
 2   displacement  398 non-null    float64
 3   horsepower    392 non-null    float64
 4   weight        398 non-null    int64
 5   acceleration  398 non-null    float64
 6   model_year    398 non-null    int64
 7   origin        398 non-null    str
 8   name          398 non-null    str
dtypes: float64(4), int64(3), str(2)
memory usage: 28.1 KB

In [8]:
df.dropna(inplace=True)
df.info()

<class 'pandas.DataFrame'>
Index: 392 entries, 0 to 397
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   mpg           392 non-null    float64
 1   cylinders     392 non-null    int64
 2   displacement  392 non-null    float64
 3   horsepower    392 non-null    float64
 4   weight        392 non-null    int64
 5   acceleration  392 non-null    float64
 6   model_year    392 non-null    int64
 7   origin        392 non-null    str
 8   name          392 non-null    str
dtypes: float64(4), int64(3), str(2)
memory usage: 30.6 KB

In [9]:
df['name']

0      chevrolet chevelle malibu
1              buick skylark 320
2             plymouth satellite
3                  amc rebel sst
4                    ford torino
                 ...
393              ford mustang gl
394                    vw pickup
395                dodge rampage
396                  ford ranger
397                   chevy s-10
Name: name, Length: 392, dtype: str

In [10]:
df[['name']]

                          name
0    chevrolet chevelle malibu
1            buick skylark 320
2           plymouth satellite
3                amc rebel sst
4                  ford torino
..                         ...
393            ford mustang gl
394                  vw pickup
395              dodge rampage
396                ford ranger
397                 chevy s-10

[392 rows x 1 columns]

In [11]:
df[['name','origin','model_year','mpg']]

                          name  origin  model_year   mpg
0    chevrolet chevelle malibu     usa          70  18.0
1            buick skylark 320     usa          70  15.0
2           plymouth satellite     usa          70  18.0
3                amc rebel sst     usa          70  16.0
4                  ford torino     usa          70  17.0
..                         ...     ...         ...   ...
393            ford mustang gl     usa          82  27.0
394                  vw pickup  europe          82  44.0
395              dodge rampage     usa          82  32.0
396                ford ranger     usa          82  28.0
397                 chevy s-10     usa          82  31.0

[392 rows x 4 columns]

In [12]:
df_head=df.head()
df_head.set_index('name',inplace=True)
df_head

,mpg,cylinders,displacement,horsepower,weight,acceleration,model_year,origin
name,,,,,,,,
chevrolet chevelle malibu,18.0,8,307.0,130.0,3504,12.0,70,usa
buick skylark 320,15.0,8,350.0,165.0,3693,11.5,70,usa
plymouth satellite,18.0,8,318.0,150.0,3436,11.0,70,usa
amc rebel sst,16.0,8,304.0,150.0,3433,12.0,70,usa
ford torino,17.0,8,302.0,140.0,3449,10.5,70,usa

In [13]:
#'iloc' and 'loc' are the two indexing techniques that help us in selecting specific rows and columns.

# iloc- Access a group of rows and columns by integer index.
# Syntax - df.iloc[Rows, Columns]
df.iloc[2,1]

8

In [14]:
df.iloc[2,-1]

'plymouth satellite'

In [ ]:
df.iloc[1:5 , 4:6]  #Row:1->5 Col:4->6

   weight  acceleration
1    3693          11.5
2    3436          11.0
3    3433          12.0
4    3449          10.5

In [ ]:
#   loc- Access a group of rows and columns by custom index.

df_head = df.head()
df_head.set_index('name' , inplace=True)
df_head.loc['buick skylark 320': 'amc rebel sst']

,mpg,cylinders,displacement,horsepower,weight,acceleration,model_year,origin
name,,,,,,,,
buick skylark 320,15.0,8,350.0,165.0,3693,11.5,70,usa
plymouth satellite,18.0,8,318.0,150.0,3436,11.0,70,usa
amc rebel sst,16.0,8,304.0,150.0,3433,12.0,70,usa

In [20]:
# Note: While retrieving records using loc, the upper range of slice is inclusive.

df.loc[0:5 , ['cylinders','horsepower','name']]

   cylinders  horsepower                       name
0          8       130.0  chevrolet chevelle malibu
1          8       165.0          buick skylark 320
2          8       150.0         plymouth satellite
3          8       150.0              amc rebel sst
4          8       140.0                ford torino
5          8       198.0           ford galaxie 500

In [21]:
#The teacher wants to insert a ‘Total marks’ column which gives the sum of marks of all subjects.

marks = {'Chemistry': [67,90,66,32], 
        'Physics': [45,92,72,40],  
        'Mathematics': [50,87,81,12],  
        'English': [19,90,72,68]}

marks_df = pd.DataFrame(marks , index=['Subodh','Ram','Abdul','John'])
marks_df

        Chemistry  Physics  Mathematics  English
Subodh         67       45           50       19
Ram            90       92           87       90
Abdul          66       72           81       72
John           32       40           12       68

In [25]:
marks_df['Total']=marks_df['Chemistry']+marks_df['Physics']+marks_df['Mathematics']+marks_df['English']
marks_df

        Chemistry  Physics  Mathematics  English  Total
Subodh         67       45           50       19    181
Ram            90       92           87       90    359
Abdul          66       72           81       72    291
John           32       40           12       68    152

In [26]:
marks_df.drop(columns='Total' , inplace=True)
marks_df

        Chemistry  Physics  Mathematics  English
Subodh         67       45           50       19
Ram            90       92           87       90
Abdul          66       72           81       72
John           32       40           12       68