Broadcasting refers to a set of rules to operate between data of different sizes and shapes.

Problem Statement:
The teacher wants to award five bonus marks to all the students.

In [2]:
import pandas as pd 
import numpy as np

In [3]:
marks = {'Chemistry': [67,90,66,32], 
        'Physics': [45,92,72,40],  
        'Mathematics': [50,87,81,12],  
        'English': [19,90,72,68]}

marks_df = pd.DataFrame(marks,index=['Ramesh','Suresh','Namesh','Naresh'])
marks_df

        Chemistry  Physics  Mathematics  English
Ramesh         67       45           50       19
Suresh         90       92           87       90
Namesh         66       72           81       72
Naresh         32       40           12       68

In [5]:
new_marks_df = marks_df+5
new_marks_df

        Chemistry  Physics  Mathematics  English
Ramesh         72       50           55       24
Suresh         95       97           92       95
Namesh         71       77           86       77
Naresh         37       45           17       73

Problem Statement:
The teacher wants to increase the marks of all the students as follows-

Chemistry: + 5

Physics: + 10

Mathematics: +10

English: + 2

In [10]:
new_marks_df = marks_df +[5,10,10,2]
new_marks_df

        Chemistry  Physics  Mathematics  English
Ramesh         72       55           60       21
Suresh         95      102           97       92
Namesh         71       82           91       74
Naresh         37       50           22       70

Apply
This method is used to apply a function along an axis of the DataFrame.

Syntax:

       DataFrame.apply(func, axis = 0, result_type = None)

       func : Function to apply to each column or row.

       axis: Axis along which the function is applied.

       result_type: one out of 'expand', 'reduce' or 'broadcast'. In the demo, 'broadcast' is used.

‘broadcast’ : results will be broadcast to the original shape of the DataFrame, the original index and columns will be retained

In [13]:
#Creating the DataFrame
marks = {'Chemistry': [67,90,66,32], 
        'Physics': [45,92,72,40],  
        'Mathematics': [50,87,81,12],  
        'English': [19,90,72,68]}
marks_df = pd.DataFrame(marks, index = ['James', 'Lee', 'Anderson', 'John'])
marks_df

          Chemistry  Physics  Mathematics  English
James            67       45           50       19
Lee              90       92           87       90
Anderson         66       72           81       72
John             32       40           12       68

Problem statement : 
The teacher wants to get the total marks scored in each subject

In [12]:
marks_df.apply(np.sum , axis=0) # sum of each column

Chemistry      255
Physics        249
Mathematics    230
English        249
dtype: int64

Problem statement: 
The teacher wants to get the total marks scored by each student.

In [14]:
marks_df.apply(np.sum , axis=1) # sum of each row

James       181
Lee         359
Anderson    291
John        152
dtype: int64

Problem Statement:
The students were unable to attend the next set of exams due to the pandemic. Hence, the teacher decides to award them average marks based on their previous performance.

In [15]:
marks_df.apply(np.mean , axis=0 , result_type='broadcast') # mean of each column

          Chemistry  Physics  Mathematics  English
James            63       62           57       62
Lee              63       62           57       62
Anderson         63       62           57       62
John             63       62           57       62