# Problem Statement:
The teacher wants to encrypt the marks for confidential reasons. Therefore, the teacher decides to save the marks as sine of the original marks. For example, if Subodh has scored 67 in chemistry, then his encrypted marks will be sin(67) = -0.855520

In [8]:
import pandas as pd
import numpy as np

In [5]:
marks = {'Chemistry': [67,90,66,32], 
        'Physics': [45,92,72,40],  
        'Mathematics': [50,87,81,12],  
        'English': [19,90,72,68]}

marks_df = pd.DataFrame(marks,index=['Ramesh','Suresh','Namesh','Naresh'])
marks_df

        Chemistry  Physics  Mathematics  English
Ramesh         67       45           50       19
Suresh         90       92           87       90
Namesh         66       72           81       72
Naresh         32       40           12       68

In [ ]:
# encripting marks as sine of marks 
#The  encrypted marks are with same indices as the original marks. This is called as index preservation.
encrypted_marks= np.sin(marks_df)
encrypted_marks

        Chemistry   Physics  Mathematics   English
Ramesh  -0.855520  0.850904    -0.262375  0.149877
Suresh   0.893997 -0.779466    -0.821818  0.893997
Namesh  -0.026551  0.253823    -0.629888  0.253823
Naresh   0.551427  0.745113    -0.536573 -0.897928

# Resetting Index:
In case of a requirement where the index has to be restored to the default index, reset_index() function must be used. It adds the existing index as a new column in the DataFrame. This can be done as follows

In [12]:
encrypted_marks.reset_index(inplace=True)
encrypted_marks

    index  Chemistry   Physics  Mathematics   English
0  Ramesh  -0.855520  0.850904    -0.262375  0.149877
1  Suresh   0.893997 -0.779466    -0.821818  0.893997
2  Namesh  -0.026551  0.253823    -0.629888  0.253823
3  Naresh   0.551427  0.745113    -0.536573 -0.897928