join() Function

Purpose:

Used to combine two DataFrames based on the index instead of columns.
Efficient when working with indexed data.
Usage:

When merging DataFrames based on index values.
When quickly joining hierarchical or time-series data.

Syntax:

df1.join(df2, how='left', on=None)

In [2]:
import pandas as pd
import numpy as np

In [3]:
# Sample DataFrames
df1 = pd.DataFrame({'key': ['A', 'B', 'C', 'D'], 'col1': [1, 2, 3, 4]})
df2 = pd.DataFrame({'key': ['B', 'C', 'D', 'E'], 'col2': [5, 6, 7, 8]})
print("Data Frame -1 \n", df1)
print("Data Frame -2\n",df2)

Data Frame -1
   key  col1
0   A     1
1   B     2
2   C     3
3   D     4
Data Frame -2
   key  col2
0   B     5
1   C     6
2   D     7
3   E     8

In [4]:
#1. Inner Merge
inner_join = pd.merge(df1,df2,on='key', how='inner')
inner_join

  key  col1  col2
0   B     2     5
1   C     3     6
2   D     4     7

In [5]:
##2. Outer Merge
outer_merge = pd.merge(df1,df2,on='key',how='outer')
outer_merge

  key  col1  col2
0   A   1.0   NaN
1   B   2.0   5.0
2   C   3.0   6.0
3   D   4.0   7.0
4   E   NaN   8.0

In [6]:
# left merge
left_merge= pd.merge(df1,df2,on='key',how='left')
left_merge

  key  col1  col2
0   A     1   NaN
1   B     2   5.0
2   C     3   6.0
3   D     4   7.0

In [7]:
#right merge
right_merge = pd.merge(df1,df2,on='key',how='right')
right_merge

  key  col1  col2
0   B   2.0     5
1   C   3.0     6
2   D   4.0     7
3   E   NaN     8

In [8]:
# --- Join Operations (assuming 'key' is the index in both DataFrames) ---
df_1=df1.set_index('key')
df_2= df2.set_index('key')
print("Data Frame -1 \n", df_1)
print("Data Frame -2\n",df_2)

Data Frame -1
      col1
key
A       1
B       2
C       3
D       4
Data Frame -2
      col2
key
B       5
C       6
D       7
E       8

In [9]:
#1. inner join 
inner_join = df_1.join(df_2,how='inner')
inner_join

     col1  col2
key
B       2     5
C       3     6
D       4     7

In [10]:
# 2.outer join
outer_join = df_1.join(df_2,how='outer')
outer_join

     col1  col2
key
A     1.0   NaN
B     2.0   5.0
C     3.0   6.0
D     4.0   7.0
E     NaN   8.0

In [11]:
#3.left join
left_join = df_1.join(df_2,how='left')
left_join

     col1  col2
key
A       1   NaN
B       2   5.0
C       3   6.0
D       4   7.0

In [12]:
#4.right join 
right_join = df_1.join(df_2,how='right')
right_join

     col1  col2
key
B     2.0     5
C     3.0     6
D     4.0     7
E     NaN     8